from __future__ import annotations

import argparse
import importlib
import inspect
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

MODULES: Sequence[str] = (
    "modulus",
    "modulus.optim",
    "modulus.optim.hyperball",
    "modulus.optim.groups",
    "modulus.optim.masks",
    "modulus.optim.schedules",
    "modulus.optim.presets",
    "modulus.peft",
    "modulus.peft.lora",
    "modulus.training",
    "modulus.training.harness",
)


@dataclass(frozen=True)
class ApiItem:
    kind: str
    name: str
    signature: str
    doc: str


def _first_paragraph(doc: str | None) -> str:
    if not doc:
        return "No documentation available."
    text = inspect.cleandoc(doc).strip()
    if not text:
        return "No documentation available."
    return text.split("\n\n")[0].replace("\n", " ").strip()


def _build_items(module_name: str) -> list[ApiItem]:
    mod = importlib.import_module(module_name)
    out: list[ApiItem] = []
    for name, obj in inspect.getmembers(mod):
        if name.startswith("_"):
            continue
        if inspect.isfunction(obj):
            if obj.__module__ != module_name:
                continue
            out.append(
                ApiItem(
                    kind="function",
                    name=name,
                    signature=_stable_signature(obj),
                    doc=_first_paragraph(inspect.getdoc(obj)),
                )
            )
        elif inspect.isclass(obj):
            if obj.__module__ != module_name:
                continue
            out.append(
                ApiItem(
                    kind="class",
                    name=name,
                    signature=_stable_signature(obj),
                    doc=_first_paragraph(inspect.getdoc(obj)),
                )
            )
    return out


def _stable_signature(obj: object) -> str:
    try:
        sig = str(inspect.signature(obj))
    except Exception:
        return "()"
    # Remove runtime-specific function memory addresses from defaults.
    return re.sub(r"<function ([^>]+) at 0x[0-9A-Fa-f]+>", r"<function \1>", sig)


def _module_page(module_name: str) -> str:
    mod = importlib.import_module(module_name)
    mod_doc = _first_paragraph(inspect.getdoc(mod))
    items = _build_items(module_name)

    lines: list[str] = []
    lines.append(f"# API: `{module_name}`")
    lines.append("")
    lines.append("- Generated by: `scripts/generate_api_docs.py`")
    lines.append("- Source of truth: Python module introspection")
    lines.append("")
    lines.append("## Purpose")
    lines.append("")
    lines.append(mod_doc)
    lines.append("")
    lines.append("## Public API")
    lines.append("")

    if not items:
        lines.append("No public classes/functions discovered in this module.")
        lines.append("")
        return "\n".join(lines)

    for item in items:
        lines.append(f"### `{item.name}`")
        lines.append("")
        lines.append(f"- Kind: `{item.kind}`")
        lines.append(f"- Signature: `{item.name}{item.signature}`")
        lines.append("")
        lines.append(item.doc)
        lines.append("")
    return "\n".join(lines)


def _index_page() -> str:
    lines: list[str] = []
    lines.append("# API Reference (Auto-Generated)")
    lines.append("")
    lines.append("- Generator: `scripts/generate_api_docs.py`")
    lines.append("")
    lines.append("## Modules")
    lines.append("")
    for module_name in MODULES:
        filename = module_name.replace(".", "_") + ".md"
        lines.append(f"- [{module_name}](./{filename})")
    lines.append("")
    lines.append("## Regeneration")
    lines.append("")
    lines.append("```bash")
    lines.append("python scripts/generate_api_docs.py")
    lines.append("```")
    lines.append("")
    lines.append("Check freshness (CI mode):")
    lines.append("")
    lines.append("```bash")
    lines.append("python scripts/generate_api_docs.py --check")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def _render_all() -> dict[Path, str]:
    out_dir = Path("docs/api_generated")
    rendered: dict[Path, str] = {}
    rendered[out_dir / "INDEX.md"] = _index_page()
    for module_name in MODULES:
        filename = module_name.replace(".", "_") + ".md"
        rendered[out_dir / filename] = _module_page(module_name)
    return rendered


def _write(rendered: dict[Path, str]) -> None:
    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def _check(rendered: dict[Path, str]) -> int:
    stale: list[Path] = []
    for path, expected in rendered.items():
        if not path.exists():
            stale.append(path)
            continue
        current = path.read_text(encoding="utf-8")
        if current != expected:
            stale.append(path)
    if stale:
        print("API docs out of date:")
        for p in stale:
            print(f"- {p}")
        print("Run: python scripts/generate_api_docs.py")
        return 1
    print("API docs are up to date.")
    return 0


def parse_args(argv: Iterable[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate or check auto API docs.")
    p.add_argument("--check", action="store_true", help="Fail if generated docs differ from disk.")
    return p.parse_args(argv)


def main() -> int:
    args = parse_args()
    rendered = _render_all()
    if args.check:
        return _check(rendered)
    _write(rendered)
    print(f"Wrote {len(rendered)} API doc files to docs/api_generated/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
